include: package:flutter_lints/flutter.yaml


analyzer:
  errors:
    prefer_single_quotes: error
    avoid_print: error
    prefer_relative_imports : error
    unused_import : error


linter:
  rules:
    prefer_single_quotes: true
    prefer_double_quotes: false
    prefer_const_constructors: true
    avoid_relative_lib_imports: false
    always_use_package_imports: false
    sort_child_properties_last: true
    prefer_is_not_empty: true
    prefer_inlined_adds: true
    # omit_local_variable_types: true
    # prefer_if_elements_to_conditional_expressions: true
    prefer_conditional_assignment: true
    prefer_const_literals_to_create_immutables: true
    avoid_catches_without_on_clauses: true
    avoid_redundant_argument_values: true
    avoid_returning_null: true
    prefer_adjacent_string_concatenation: false
    prefer_final_fields: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_int_literals: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    sort_constructors_first: true
    unnecessary_brace_in_string_interps: true
    unnecessary_lambdas: true
    unnecessary_new: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    avoid_void_async: true
    await_only_futures: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    missing_whitespace_between_adjacent_strings: true
    unnecessary_getters_setters: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    use_string_buffers: true
